# Generated by Django 3.1.5 on 2021-12-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banglore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('team', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='chennai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('team', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='delhi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('team', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='hyderabad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('team', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='kolkata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('team', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='mumbai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('team', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='punjab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('team', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='rajasthan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('team', models.CharField(max_length=20)),
            ],
        ),
    ]
