# Generated by Django 3.1.5 on 2021-12-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPLWebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_name', models.CharField(max_length=20)),
                ('player_name', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
